# Generated by Django 4.1.7 on 2023-12-26 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="name",
            new_name="business_name",
        ),
    ]
