# Generated by Django 4.1.7 on 2023-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0005_remove_business_project_business_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="refers",
            field=models.ManyToManyField(
                blank=True, related_name="referred_by", to="businesses.product"
            ),
        ),
    ]
