# Generated by Django 4.1.7 on 2023-12-27 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0006_alter_business_refers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="refers",
        ),
    ]
